[package]
name = "io-surface"
version = "0.1.0"
authors = ["The Servo Project Developers"]
license = "MIT / Apache-2.0"

[dependencies]
libc = "*"
gleam = "0.1"
euclid = "0.1"

[target.x86_64-apple-darwin.dependencies]
core-foundation = "*"
cgl = "0.1"
